services:

  app:
    build: .
    ports: 
      - "5000:5000"
    env_file:
      - .env
    
    depends_on:
       db:
        condition: service_healthy

  db:
    image: mysql:8.0
    ports:
    - "3308:3306"
    env_file:
    - .env
    volumes:
      - /mi_datos_sql:/var/lib/mysql
   


    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
  